// Auto-generated by scripts/generate-route-types.ts
// Last updated: 2024-01-15T10:30:00.000Z
// Do not edit manually

export type AppRoute = "/" | "/dashboard" | "/settings" | "/users" | "/users/[id]"

// Typed routes object
export const ROUTES = {
  ROOT: "/" as const,
  DASHBOARD: "/dashboard" as const,
  SETTINGS: "/settings" as const,
  USERS: "/users" as const,
  USERS_ID: "/users/[id]" as const,
} as const

// Route validation function
export function isValidRoute(route: string): route is AppRoute {
  return ["/", "/dashboard", "/settings", "/users", "/users/[id]"].includes(route as AppRoute)
}

// Get all available routes
export function getAllRoutes(): AppRoute[] {
  return ["/", "/dashboard", "/settings", "/users", "/users/[id]"]
}
